package javaCC;

/* Generated By:JavaCC: Do not edit this line. AnalisadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ponto_virg = 4;
  /** RegularExpression Id. */
  int VAZIO = 5;
  /** RegularExpression Id. */
  int PALAVRAS_RESERVADAS = 6;
  /** RegularExpression Id. */
  int COMANDOS = 7;
  /** RegularExpression Id. */
  int TIPOS_DE_DADOS = 8;
  /** RegularExpression Id. */
  int NUMEROS = 9;
  /** RegularExpression Id. */
  int IDENTIFICADORES = 10;
  /** RegularExpression Id. */
  int OPERADORES = 11;
  /** RegularExpression Id. */
  int COMPARADORES = 12;
  /** RegularExpression Id. */
  int ABRE_COLCHETE = 13;
  /** RegularExpression Id. */
  int FECHA_COLCHETE = 14;
  /** RegularExpression Id. */
  int TERMINAIS = 15;
  /** RegularExpression Id. */
  int ABRE_PARENTESE = 16;
  /** RegularExpression Id. */
  int FECHA_PARENTESE = 17;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 18;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\" \"",
    "<PALAVRAS_RESERVADAS>",
    "<COMANDOS>",
    "<TIPOS_DE_DADOS>",
    "<NUMEROS>",
    "<IDENTIFICADORES>",
    "<OPERADORES>",
    "<COMPARADORES>",
    "\"[\"",
    "\"]\"",
    "<TERMINAIS>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
